### ISSUE TITLE
Back-end API document

### ISSUE THREAD

**Issue by shivasaki** [hiromuota166/kuromalun#23]
### As Is
バックエンドの仕様は @Chiro358 が把握しており他の人はコードから推測するか尋ねる必要がある

### To Be 
チーム内の誰でもAPIリファレンスを見ることができ、それでバックエンドの仕様を把握できる

### アクション
ドキュメントの形式を決める、 @Chiro358 が書く

### 課題
形式を決めるの難しい

**Comment by Chiro358** [comment]
リファレンスってpythonのファイルごとに説明をつけるってイメージでいいですか？

**Comment by shivasaki** [comment]
> リファレンスってpythonのファイルごとに説明をつけるってイメージでいいですか？

いいえ、リファレンスドキュメントを作成してほしいです
e.g., [LINE Messaging API](https://developers.line.biz/ja/reference/messaging-api/), [GitHub Git REST API](https://docs.github.com/ja/rest/git/refs?apiVersion=2022-11-28)

具体的な方法はチームで話し合ってから

**Comment by Chiro358** [comment]
了解です
